### ISSUE TITLE
not workking

### ISSUE THREAD

**Issue by dfgdrtgdrfg** [jbehrens94/PrivacyApp#2] opened 2015-08-25 17:48 UTC
![error](https://cloud.githubusercontent.com/assets/10977094/9474650/9885ef96-4b6a-11e5-9e8b-b9b79aac97d6.png)

**Comment by jbehrens94** [comment] 2015-08-25 19:05
I am not able to help and identify your error and I can't reproduce your steps.
Therefore I am going to close this issue.

**Closed by jbehrens94** 2015-08-25 19:05 UTC

**Comment by dfgdrtgdrfg** [comment] 2015-08-26 08:26
I  just  run  it  normal with  version  Xcode  6  and   don’t even  start  the  simulator  for  iphone.


Savu Andreea
savuandreea1@gmail.com
